"""Milestone 1 acceptance tests: the library ontology.

You do not edit this file. You write library_agent/ontology.py until
every test passes. Run from the project root:  pytest -v
"""

from library_agent.ontology import (
    NODE_TYPES,
    RELATIONSHIPS,
    validate_node,
    validate_relationship,
)


# --- The rulebook: node types ------------------------------------------------
def test_all_eight_node_types_exist():
    assert set(NODE_TYPES) == {
        "Book", "Author", "Genre", "Member", "Branch",
        "Loan", "AvailabilityStatement", "Perspective",
    }


def test_every_node_type_has_a_key_that_is_also_required():
    for label, spec in NODE_TYPES.items():
        assert spec["key"] in spec["required"], f"{label}: the key must be required"


def test_keys_are_correct():
    keys = {label: spec["key"] for label, spec in NODE_TYPES.items()}
    assert keys == {
        "Book": "isbn", "Author": "name", "Genre": "name", "Member": "member_id",
        "Branch": "name", "Loan": "loan_id", "AvailabilityStatement": "statement_id",
        "Perspective": "perspective_id",
    }


# --- The rulebook: relationships ---------------------------------------------
def test_all_eight_relationships_exist():
    assert RELATIONSHIPS == {
        ("Author", "WROTE", "Book"),
        ("Book", "IN_GENRE", "Genre"),
        ("Book", "SEQUEL_OF", "Book"),
        ("Member", "HAS_LOAN", "Loan"),
        ("Loan", "FOR_BOOK", "Book"),
        ("Loan", "AT_BRANCH", "Branch"),
        ("AvailabilityStatement", "ABOUT", "Book"),
        ("AvailabilityStatement", "ACCORDING_TO", "Perspective"),
    }


# --- validate_node -----------------------------------------------------------
def test_valid_book():
    assert validate_node("Book", {"isbn": "978-1", "title": "The Desert Star"}) == []


def test_extra_properties_are_allowed():
    assert validate_node("Book", {"isbn": "978-1", "title": "X", "year": 2020}) == []


def test_book_missing_title():
    assert validate_node("Book", {"isbn": "978-1"}) == [
        "Book is missing required property 'title'"
    ]


def test_empty_string_counts_as_missing():
    assert validate_node("Member", {"member_id": "M001", "name": ""}) == [
        "Member is missing required property 'name'"
    ]


def test_loan_missing_two_properties():
    assert validate_node("Loan", {}) == [
        "Loan is missing required property 'loan_id'",
        "Loan is missing required property 'status'",
    ]


def test_unknown_node_type():
    assert validate_node("Magazine", {"name": "Weekly"}) == ["Unknown node type: Magazine"]


# --- validate_relationship ---------------------------------------------------
def test_allowed_relationship():
    assert validate_relationship("Book", "SEQUEL_OF", "Book") == []


def test_unknown_source_type():
    assert validate_relationship("Magazine", "WROTE", "Book") == ["Unknown node type: Magazine"]


def test_unknown_target_type():
    assert validate_relationship("Author", "WROTE", "Magazine") == ["Unknown node type: Magazine"]


def test_relationship_not_in_ontology():
    assert validate_relationship("Member", "WROTE", "Book") == [
        "Relationship not allowed: (Member)-[:WROTE]->(Book)"
    ]


def test_direction_matters():
    # A book does not write an author
    assert validate_relationship("Book", "WROTE", "Author") == [
        "Relationship not allowed: (Book)-[:WROTE]->(Author)"
    ]
